### ISSUE TITLE
Trouble pinning/ installing

### ISSUE THREAD

**Issue by wiredsister** [verbosemode/syslogd-mirage#1]
After pinning, it prompts for an opam file. I've tried a few different variations of this file, but am not sure if I need to do something specific for building?

Then when I run 
`mirage configure --unix --net=socket --port=5514`
it cannot generate the Makefile because it fails at: 

``` [ERROR]
command terminated with exit code 2
stderr: ocamlfind: Package `syslog-message' not found
```

So, my install wasn't proper methinks.

Can we either include an opam file, or tell steps for what that should look like? 
Just having trouble making this work with instructions given. 
Thanks.

PS: Is there somewhere I can find a backlog of things this project needs to accomplish? Would love to pick something off.

**Comment by verbosemode** [comment]
Thanks for spotting this issue. Adding ".git" to the URL should fix the issue regarding pinning the syslog-message package.

opam pin add syslog-message https://github.com/verbosemode/syslog-message.git

I'll answer your other questions within the next few hours. Need to grab some lunch first :D

**Comment by wiredsister** [comment]
Someone just told me you're coming!! Can't wait to hack with you. We'll figure it out in person.

**Comment by verbosemode** [comment]
Indeed. I'm definitely looking forward to it. Unfortunately I had to postpone my flight and will now arrive on Sunday at around 3 pm.

We've discussed some of the wanted features on the mailinglist here: http://thread.gmane.org/gmane.os.mirage.devel/1492

At the top of the list is a storage backend via Irmin. But I would also need to read up on it since I'm still a beginner in regards to OCaml and MirageOS.

**Comment by wiredsister** [comment]
Cool. I'm a newbie too. 
I'm looking at the Irmin API now. Maybe a good start is an in-memory store....

**Comment by Leonidas-from-XIV** [comment]
Tried pinning the correct URL now and it worked for me (modulo some nonreproducible failure that I blame on myself).

**Comment by wiredsister** [comment]
@Leonidas-from-XIV same here. Works after correct URL. Closing this.
