### ISSUE TITLE
Self contained example please

### ISSUE THREAD

**Issue by fxfactorial** [verbosemode/syslogd-mirage#8]
Great work on syslog. 

I was wondering if a self contained example could be presented, maybe even something chewy like integration with canopy.

**Comment by wiredsister** [comment]
I think that's a nice idea. Maybe not something possible in the short term, but certainly in the next month. 

What exactly would you like to see it do with Canopy? Like pointing Canopy at the remote URI of a syslog collection of events to display? I'm pretty sure the only hard limit for Canopy is this must be the format: 

``` markdown
---
title: A blog entry
author: Me
abstract: A simple line telling what this article is all about, will be displayed in listing pages. (optional)
---
article content
```

So we could add some glue before it makes commits to output format that way.

**Comment by fxfactorial** [comment]
Oh I forgot that canopy is just generating HTML, I thought it also served it? 

Just in the general idea, make an example such that we could see in real time via syslog what people were visiting a blog post, their IP etc etc. I suppose that becomes quite a meaty example, but very much real world usage.

**Comment by wiredsister** [comment]
That would indeed be a great sell. The thing is, right now we aren't doing any sending of events, just collecting on the host. So I think we might be a ways away from that, but ultimately by the end of my internship I think that would be the goal-- to have an all encompassing, knock-out syslog example.
